AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "Gemfile"
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
MethodLength:
  CountComments: true
  Max: 24
Naming/MethodParameterName:
  Enabled: false
