AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "Gemfile"
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  CountComments: true
  Max: 24
  Exclude:
  - "db/migrate/*.rb"
Naming/MethodParameterName:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
